baseURL = 'https://suomisiirtyy.fi/'
languageCode = 'fi'
title = 'Suomi siirtyy'
theme = 'suomisiirtyy'

[menus]
  [[menus.main]]
    name = 'Etusivu'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Vaihtoehdot'
    pageRef = '/vaihtoehdot'
    weight = 20

  [[menus.main]]
    name = 'Digitaalinen autonomia'
    pageRef = '/digitaalinen-autonomia'
    weight = 30

  [[menus.main]]
    name = 'Mitä voin tehdä?'
    pageRef = '/mita-voin-tehda'
    weight = 40

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'
